### ISSUE TITLE
Donation Portal

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/blpress.org-archive-wp#1]
We've realized that in addition to creating new email addresses, we'll also need to update the donation portal this summer (right now, the "Donate Now" button leads to an NYU page). Is this something you could handle for us, and would you recommend working with a certain money-paying engine (like PayPal)? How much would this cost for the one-time setup and any monthly/per donation fees?

**Comment by AdamChlan** [comment]
@budparr since Gravity Forms is already on the site, this could be a good way to go. We'd just need to settle on a payment processor.

**Comment by AdamChlan** [comment]
Form is set up. SSL generation is underway. Waiting for registrar access. Also waiting for BLPress to finish adding their banking info to Strip so we can run in Live mode.

**Comment by AdamChlan** [comment]
Confirming DNS is switched to Cloudflare, and SSL is set up. All traffic is https now. I will share the donation form page I set up for feedback.

**Comment by budparr** [comment]
Awesome. Can you also let them know about the SSL when you tell them about the donation page?

**Comment by AdamChlan** [comment]
Client informed about SSL, and currently reviewing the donation page

**Comment by AdamChlan** [comment]
This is live. Closing out.
