### ISSUE TITLE
Email Sign up form overlapping footer area 

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/blpress.org-archive-wp#2]
<img width="1432" alt="screen shot 2018-05-18 at 11 29 37 am" src="https://user-images.githubusercontent.com/115347/40243692-e7279c9a-5a8e-11e8-8a98-e847f4543292.png">

**Comment by AdamChlan** [comment]
This is all set.
<img width="1355" alt="screenshot 2018-05-29 10 21 16" src="https://user-images.githubusercontent.com/757209/40664951-140702c0-632a-11e8-890a-be50e5c47c24.png">
