### ISSUE TITLE
Non-profit Google Account Support

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/blpress.org-archive-wp#5]
@budparr adding some notes for our records of work done for BLPress.

Earlier this week Elana let me know that there Non-Profit account was suspended because the trial ran out. I contacted Google support through chat and got them to reactivate the account, and they said she should get a confirmation email in the coming days indicating that things are straightened out. I'm checking with Elana to see if she got that communication yet.

**Comment by budparr** [comment]
Thanks!

**Comment by AdamChlan** [comment]
Closing out. Elana got the confirmation email.
