### ISSUE TITLE
WooCommerce Update

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/blpress.org-archive-wp#6]
Updating to the latest version of WooCommerce plugin breaks, the following layouts, which need to be fixed:

- [x] https://blpress.org/books/ (book list view)

- [x] https://blpress.org/books/murmur/ (book detail)

**Comment by budparr** [comment]
@AdamChlan Is there anything you need me to do on those?

**Comment by AdamChlan** [comment]
I don't want to put you through that ;-) 

I am struggling a bit trying to get WooCommerce to cooperate, and track down the template files that need to be updated, but I'll keep plugging.
