### ISSUE TITLE
Adding Affiliate Links to our website

### ISSUE THREAD

**Issue by AdamChlan** [theNewDynamic/blpress.org-archive-wp#9]
I'm checking in with you to see how we might go about adding affiliate links to our site. We used to be set up to do this, but have let it lapse.

**Comment by AdamChlan** [comment]
@budparr below is an example of what a text based affiliate link looks like:

`<a target="_blank" href="https://www.amazon.com/gp/product/194265846X/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=194265846X&linkCode=as2&tag=egoldman-20&linkId=84b3d06543b0b720c5715df44b2af182">Feast Day of the Cannibals (The American Novels)</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=egoldman-20&l=am2&o=1&a=194265846X" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />`

Amazon provides a tool to create this code. It seems to me if they want to go this route, we would remove the code that currently generates the link to amazon based on the ISBN number, and I'd update it to use the link above. Before I do anything like this, I'm curious to know your thoughts on this change. Let's chat on Monday about it.

**Comment by budparr** [comment]
@AdamChlan I think that's a lot of cruft. I think we just add the affiliate ID to the automated links. I see this: `&tag=egoldman-20` in that link. Tag doesn't strike me as being right, but that might be it.

**Comment by AdamChlan** [comment]
I'd much rather do something like this. I'll review the tag, and look at testing/confirming

**Comment by AdamChlan** [comment]
links added for Amazon, B&N and Indiebound. Closing out
